import type { StoredConsent, ConsentConfig, CookieConfigDefaults, ConsentStorage } from "./types";
import { DEFAULT_CONFIG } from "./types";

/**
 * Get cookie value by name
 */
export function getCookie(name: string): string | null {
  if (typeof document === "undefined") return null;

  const cookies = document.cookie.split(";");
  for (const cookie of cookies) {
    const [key, value] = cookie.trim().split("=");
    if (key === name) {
      return decodeURIComponent(value);
    }
  }
  return null;
}

/**
 * Set cookie with options
 */
export function setCookie(
  name: string,
  value: string,
  options: {
    expiry?: number;
    domain?: string;
    path?: string;
    sameSite?: "Strict" | "Lax" | "None";
    secure?: boolean;
  } = {}
): void {
  if (typeof document === "undefined") return;

  const { expiry = 365, domain, path = "/", sameSite = "Lax", secure = false } = options;

  let cookieString = `${name}=${encodeURIComponent(value)}`;

  if (expiry) {
    const date = new Date();
    date.setTime(date.getTime() + expiry * 24 * 60 * 60 * 1000);
    cookieString += `; expires=${date.toUTCString()}`;
  }

  if (domain) {
    cookieString += `; domain=${domain}`;
  }

  cookieString += `; path=${path}`;
  cookieString += `; SameSite=${sameSite}`;

  if (secure || sameSite === "None") {
    cookieString += "; Secure";
  }

  document.cookie = cookieString;
}

/**
 * Delete cookie
 */
export function deleteCookie(name: string, path = "/", domain?: string): void {
  if (typeof document === "undefined") return;
  let cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=${path}`;
  if (domain) cookie += `; domain=${domain}`;
  document.cookie = cookie;
}

/**
 * Get stored consent from cookie
 */
export function getStoredConsent(config: Partial<ConsentConfig> = {}): StoredConsent | null {
  const cookieName = config.cookie?.name ?? DEFAULT_CONFIG.cookie.name;
  const version = config.version ?? DEFAULT_CONFIG.version;

  const raw = getCookie(cookieName);
  if (!raw) return null;

  try {
    const stored = JSON.parse(raw) as StoredConsent;

    // Check version - if different, consent is invalid
    if (stored.version !== version) {
      return null;
    }

    return stored;
  } catch {
    return null;
  }
}

/**
 * Store consent in cookie
 */
export function storeConsent(
  consent: Omit<StoredConsent, "timestamp" | "version">,
  config: Partial<ConsentConfig> = {}
): void {
  const cookieConfig: CookieConfigDefaults = {
    ...DEFAULT_CONFIG.cookie,
    ...config.cookie,
  };
  const version = config.version ?? DEFAULT_CONFIG.version;

  const stored: StoredConsent = {
    categories: consent.categories,
    timestamp: Date.now(),
    version,
    // Preserve geo data if provided
    ...(consent.isEU !== undefined && { isEU: consent.isEU }),
    ...(consent.geoMethod && { geoMethod: consent.geoMethod }),
    ...(consent.countryCode && { countryCode: consent.countryCode }),
  };

  setCookie(cookieConfig.name, JSON.stringify(stored), {
    expiry: cookieConfig.expiry,
    domain: cookieConfig.domain,
    path: cookieConfig.path,
  });
}

/**
 * Clear stored consent
 */
export function clearConsent(config: Partial<ConsentConfig> = {}): void {
  const cookieName = config.cookie?.name ?? DEFAULT_CONFIG.cookie.name;
  const path = config.cookie?.path ?? DEFAULT_CONFIG.cookie.path;
  deleteCookie(cookieName, path, config.cookie?.domain);
}

/**
 * Get consent UID from cookie (used for KV re-identification)
 */
export function getConsentUid(): string | null {
  return getCookie("consent_uid");
}

/**
 * Set consent UID cookie for re-identification
 */
export function setConsentUid(uid: string, config: Partial<ConsentConfig> = {}): void {
  setCookie("consent_uid", uid, {
    expiry: config.cookie?.expiry ?? DEFAULT_CONFIG.cookie.expiry,
    domain: config.cookie?.domain,
    path: config.cookie?.path ?? DEFAULT_CONFIG.cookie.path,
  });
}

/**
 * Clear consent UID cookie
 */
export function clearConsentUid(config: Partial<ConsentConfig> = {}): void {
  const path = config.cookie?.path ?? DEFAULT_CONFIG.cookie.path;
  deleteCookie("consent_uid", path, config.cookie?.domain);
}

/**
 * Fetch consent from remote KV storage
 */
export async function fetchRemoteConsent(
  storageUrl: string,
  uid: string,
  version: string
): Promise<StoredConsent | null> {
  try {
    const res = await fetch(`${storageUrl}?id=${encodeURIComponent(uid)}`);
    if (!res.ok) return null;
    const data = (await res.json()) as { found?: boolean; consent?: StoredConsent };
    if (!data.found || !data.consent) return null;
    if (data.consent.version !== version) return null;
    return {
      categories: data.consent.categories,
      timestamp: data.consent.timestamp ?? Date.now(),
      version,
    };
  } catch {
    return null;
  }
}

/**
 * Push consent to remote KV storage. Returns the user ID (generated by worker if not provided).
 */
export async function pushRemoteConsent(
  storageUrl: string,
  uid: string | null,
  consent: StoredConsent
): Promise<string | null> {
  try {
    // Only send categories and version — timestamp is generated server-side by the worker
    const body: Record<string, unknown> = {
      categories: consent.categories,
      version: consent.version,
    };
    if (uid) body.id = uid;
    const res = await fetch(storageUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok) return null;
    const data = (await res.json()) as { id?: string };
    return data.id ?? null;
  } catch {
    return null;
  }
}

/**
 * Create a ConsentStorage backed by a Cloudflare KV Worker
 * (vue-privacy-worker compatible API).
 *
 * @example
 * ```ts
 * import { createKVStorage } from '@structured-world/vue-privacy';
 *
 * const manager = createConsentManager({
 *   gaId: 'G-XXXXXXXXXX',
 *   storage: createKVStorage('/api/consent'),
 * });
 * ```
 */
export function createKVStorage(url: string): ConsentStorage {
  return {
    get: (uid, version) => fetchRemoteConsent(url, uid, version),
    set: (uid, consent) => pushRemoteConsent(url, uid, consent),
  };
}
